---
title: "Methodology"
author: "Mislav Sagovac"
format: html
editor: visual
---

# Methodology overview

In this section we provide structured approach to develop the business model, including data collection, analysis and stakeholder engagement.

## Data collection
The development of a comprehensive business plan for biodiversity conservation within the DaWetRest project necessitates a robust data collection methodology. This approach integrates diverse data sources to paint a full picture of the economic, environmental, and social landscape of Draž Municipality and its surrounding areas, with a focus on leveraging the Danube's water potentials for sustainable development. The following outlines the methodology for collecting data from seven critical sources.
### Data from the Court Registry
The court registry serves as a primary source of information on businesses activity within Draž Municipality and surrounding areas. Accessing this database provides insights into active business entities, their legal status, foundational dates, and operational scopes. This information underpins the analysis of the economic fabric of the area, highlighting trends in business formations, closures, and sectors of activity. The process involves automated data scraping techniques authenticated through secure token-based access, ensuring up-to-date and comprehensive data retrieval. The process involves automated data scraping.
Data from the Court Registry is important for crafting a business strategy that aligns with biodiversity conservation and economic development in Draž Municipality and its surrounding areas. This rich source of legal and organizational information about businesses provides a comprehensive overview of the active business entities, their legal status, foundational dates, and operational scopes. Such detailed data is fundamental to analyzing the economic fabric of the area, highlighting key trends in business formations, closures, and activity sectors. The importance of this information extends across several dimensions of strategic planning.
Firstly, understanding the landscape of economic activities through the lens of the Court Registry data enables precise mapping of the existing industrial and sectoral composition. This mapping is crucial for identifying where biodiversity conservation efforts can intersect beneficially with economic activities. It ensures that proposed strategies are both relevant to the local economic context and have a tangible impact. 
Secondly, the data aids in a detailed sectoral analysis, identifying key industry players and the structural dynamics within each sector. This knowledge is pivotal for developing targeted conservation strategies that engage influential businesses and leverage their roles for wider sectoral participation. Such targeted approaches are often more effective and can lead to significant sector-wide changes in practices that favor biodiversity.
In essence, the detailed data from the Court Registry is not merely informational but serves as the backbone for informed strategy development. It supports the creation of conservation and development strategies that are deeply rooted in the realities of Draž Municipality’s economic environment. By aligning environmental goals with economic dynamics, it is possible to foster a community where economic development and biodiversity conservation go hand in hand, ensuring a sustainable future for both the local economy and the natural ecosystem.


### Data from Annual Financial Statements from Financial agency (FINA)
The Financial Agency (FINA) maintains detailed annual financial statements of registered companies, offering a wealth of information on their financial health, profitability, revenue streams, and asset bases. By analyzing this data, we gain an understanding of the economic viability of businesses within the targeted regions, sectoral financial trends, and the overall economic impact of local enterprises. This strategic financial analysis will not only spotlight key economic drivers but also unearth potential pathways for embedding sustainability into the core business models of local enterprises, fostering economic practices that support biodiversity conservation.
The annual financial statements maintained by the Financial Agency (FINA) are a goldmine of information for any strategic planning, especially for initiatives like the DaWetRest project aiming to align biodiversity conservation with economic development in areas like Draž Municipality and its surroundings. These financial statements, encompassing balance sheets, profit and loss accounts, cash flows, employee numbers, business size, and industry classification, provide a comprehensive snapshot of the financial health and operational viability of businesses within the region.
The detailed financial data from FINA serves several crucial functions in the strategic planning process. Firstly, it allows for an in-depth assessment of the financial health of businesses, including their profitability, revenue generation capabilities, and asset holdings. This assessment is foundational in understanding how businesses can contribute to, or benefit from, conservation efforts. For instance, profitable businesses in sectors closely related to natural resources or those dependent on healthy ecosystems for their operations might be more inclined or better positioned to invest in biodiversity conservation projects.
Moreover, analyzing this financial data facilitates the identification of key economic drivers in Draž and surrounding municipalities. It highlights businesses and sectors that play a crucial role in the local economy, providing insights into where strategic interventions might have the most significant impact. Understanding these economic drivers is essential for devising strategies that do not merely conserve biodiversity but also contribute to the region's economic resilience and sustainability.
Additionally, the data on employee numbers and business size from FINA is invaluable in understanding the employment landscape of the region. This understanding can guide the development of biodiversity conservation strategies that also address socio-economic objectives such as job creation, skill development, and economic diversification. For example, conservation projects can be designed to create new green jobs or enhance the skills of the local workforce in sustainable practices, contributing both to the economy and the environment.
In essence, the financial data from FINA equips strategists with the insights needed to design biodiversity conservation efforts that are economically viable, socially beneficial, and environmentally sustainable. By weaving these insights into the strategic planning process, it becomes possible to develop a holistic approach to conservation that aligns with the economic realities of the target regions, ensuring that conservation efforts contribute to and benefit from the local economic dynamics.

### Data on local NGO
Dataset on non-governmental organizations (NGOs) in the area, including details such as focus areas (e.g., fisheries), along with their financial reports, provides multiple layers of insights that can significantly enrich the project's strategic foundation. Utilizing information on local NGOs opens up avenues for deeper and more meaningful stakeholder engagement. By identifying organizations with aligned missions or those working within sectors critical to the project's goals, we can establish partnerships that leverage localized knowledge and networks, enhancing the project's reach and impact. NGOs in fields such as fisheries, for example, could bring valuable expertise on sustainable practices and community-based management strategies that are essential for both biodiversity conservation and local livelihoods.
The diversity of NGOs and their respective focus areas highlighted in the register of associations can also help identify existing synergies and gaps in the local conservation and development efforts. This knowledge allows for a strategic alignment of the project’s objectives with ongoing initiatives, ensuring complementarity and avoiding duplication of efforts. Furthermore, it aids in pinpointing unaddressed needs where the project could make significant contributions, thereby optimizing resource allocation and maximizing impact.
Additionally, NGOs active in policy advocacy and public awareness campaigns can amplify the project's influence in shaping biodiversity-friendly policies and enhancing public consciousness regarding environmental conservation. Collaborating on advocacy efforts and awareness campaigns can extend the project's reach, garnering broader support for conservation initiatives and fostering a more environmentally conscious community ethos.
In essence, the register of associations offers a multifaceted view of the local NGO landscape, providing valuable insights into potential collaborators, financial dynamics, sectoral activities, community engagement opportunities, and advocacy pathways. By weaving these insights into the project’s fabric, we can foster a collaborative, informed, and strategically sound approach to biodiversity conservation that resonates with the economic and social realities of Draž Municipality and its environs.

### Family Agricultural Registry
The Family Agricultural Registry provides detailed information on agricultural practices, land use, and family-owned agricultural enterprises in the region. This data is critical for understanding the agricultural landscape, key crops, irrigation practices, and the role of agriculture in the local economy. Integrating this information into the business plan ensures that agricultural development is considered within the broader context of biodiversity conservation, particularly in terms of sustainable land use and water management practices.

### Important strategic documents
#### Strategic Development Programme of Draž Municipality
The Strategic Development Programme of Draž Municipality provides a vision for the area's future, outlining key initiatives, projects, and goals aimed at promoting sustainable development. This document is instrumental in aligning the business plan with local development objectives, ensuring that biodiversity conservation efforts complement and enhance regional development strategies. Analysis of this program enables the identification of synergies between economic development and environmental conservation goals.

The Strategic Development Programme of Draž Municipality is a cornerstone document that encapsulates the collective aspirations and development pathways envisioned for the community's future. This comprehensive program outlines a series of strategic initiatives, projects, and overarching goals dedicated to steering Draž and its surroundings towards a trajectory of sustainable and inclusive growth. The significance of this program in the context of biodiversity conservation and economic development, particularly within projects like DaWetRest, cannot be overstated.
The Strategic Development Programme is not just a document outlining goals and initiatives; it is a reflection of Draž Municipality's commitment to fostering a sustainable future. For projects like DaWetRest, it offers a framework for embedding conservation efforts within the tapestry of local development, ensuring that strategies for economic growth and environmental preservation are not only aligned but also mutually reinforcing. This strategic congruence is the key to achieving a sustainable, prosperous, and biodiverse Draž, making the Strategic Development Programme a critical tool in the planning and implementation of biodiversity conservation and economic development efforts.

#### Management Plans from the Public Institutions for Economic Development Linked to Danube Water Potentials
In our pursuit to develop and implement a comprehensive and impactful project that not only respects but also enhances the biodiversity and economic development of the Danube region, we recognize the critical importance of aligning our efforts with existing strategic frameworks and initiatives. As such, a foundational component of our project's research phase will be to diligently seek out, review, and analyze an array of management plans from public and private institutions and private SME's. These documents are pivotal in guiding our understanding and actions towards sustainable utilization and conservation of the Danube's water potentials.
Our intent is to encompass a broad spectrum of plans that directly influence the ecological health and economic vitality of the region. This will include, but not be limited to, Water Resource Management Plans, Flood Management and Mitigation Plans, Sustainable Tourism Development Plans, Agricultural Water Use Plans, Fisheries Management Plans, and Hydropower Development Plansa and Green Hatchery. Each of these documents offers invaluable insights into the current strategies, challenges, and opportunities within their respective domains, providing a rich tapestry of information to inform our project strategies.
Moreover, our commitment to integrating these diverse management plans underscores our project's holistic approach. It reflects our dedication to making informed decisions that are respectful of the Danube's complex ecosystem and the communities it supports. Through this endeavor, we aim to forge a project that is not only based on comprehensive environmental and economic research but also one that is collaborative, adaptive, and forward-thinking.

## Analysis Framework
### Descriptive Statistics and Trend Analysis
After we collect all the data listed in data source part, we will use descriptive statistical measures to summarize and understand the data collected on business entities, financial health, demographics, and other relevant metrics. Trend analysis over time will help identify patterns, such as growth or decline in business activities, changes in financial health across sectors, and demographic shifts within the municipalities of interest.
First element of descriptive analysis is visualization technique. Employ data visualization techniques to present the findings in an accessible and informative manner. This includes the use of line graphs to depict trends over time, such as the number of business entities in different municipalities, and bar charts to compare financial health indicators (e.g., revenue, profit) across sectors. Visualization aids in making complex data understandable and highlights key insights that inform strategic decision-making.
The second element contains simple statistic techniques, mostly simple linear regression techniques to explore relationships between variables of interest, such as the impact of demographic changes on business activities or the relationship between financial health indicators and conservation efforts. This can help understand trends of simple relationships between variables.

## Stakeholder Engagement
Engaging stakeholders is crucial for the success of the DaWetRest project. A structured engagement process ensures that diverse perspectives are considered in developing sustainable business models for biodiversity conservation in the Middle Danube region. This section outlines the methodologies for surveys and site location assessments.

### Visit locations and regular meetings
To effectively engage with stakeholders in Draž Municipality, especially with the local government NGOs and business entities, for determining the best-suited business model for biodiversity conservation, a structured approach to site visits plays a crucial role. These visits offer a tangible means to assess the local environment, understand stakeholder concerns and interests, and foster collaborative relationships.
We plan to visit municipality Draž, the main place for Middle Donau DEMO at least once per year.
The primary objective of conducting site visits in Draž Municipality is to gather in-depth insights into the local ecological, economic, and social context. These visits aim to assess the potential for implementing various business models, with a focus on those that can contribute to biodiversity conservation, such as sports fisheries, eco-tourism, or green hatcheries. We will present our recommendation for business solutions, but stakeholders will evaluate recommended business projects and get their feedback.
We will have regular meetings with the stakeholders and project partners to discuss the potential for various business models, soliciting their insights on ecological sustainability, economic viability, and community acceptance. We will record observations, stakeholder feedback, and any agreements or suggestions made during the site visits. 
We list here 2 already conducted meetings:
1)	Meeting at Municipality Draž from 28.08.2023. to 29.08.2023.
a)	Pre-Event Activities includeded even conceptualization and agenda development. First includes development of the event's objectives, themes, and overall structure in collaboration with key stakeholders and project leaders. AIH’s President, Hrvoje Mikulcic, played a pivotal role in defining the event's goals and ensuring alignment with DaWetRest’s objectives. Agenda Development included creation of a detailed agenda, incorporating sessions, discussions, and presentations relevant to the project's progress and future plans. Also coordination with speakers and session chairs to finalize their topics and presentation materials. Next, logistic and technical Setup has to be planned with venue, technical arrangements, communication and invitations. We sent out invitations and event details to all project beneficiaries and stakeholders that attented the meeting. Next, we set up an online registration system and managed participant confirmations and inquiries, prepared a participant list, ensuring all key stakeholders and project members were included. We have also organized pre-event briefings for speakers and session chairs, providing them with information on the event flow and technical aspects.
i)	During’Event Activities first included event management and coordination. We Facilitated session transitions, ensuring adherence to the agenda and time management. AIH’s team leader, Hrvoje Mikulcic, played a crucial role in managing the session logistics and participant interactions. We encouraged active participation and interaction among attendees during Q&A sessions and discussions. Hrvoje Mikulcic had presentation on main aspects of DaWetRest project. Mislav Sagovac had presentation on Economic and financiala aspects of the projects. He collect verz valuable information about the economic situation in the municipality. For example, stakeholders perceive fishing tourism as main economic subsector for this project. They also explained main obstacles for economic activity in the area (demography).
ii)	Post’Event Activities - compiled a comprehensive event report, summarizing discussions, key outcomes, and action items. We communicated the next steps, including the dates, agenda, and venues for the next meetings, to all stakeholders. We ensured that action items were integrated into the ongoing project management and monitoring processes.
2)	Meeting at Lonjsko Polje on 16.10.2023. 
The venue, chosen for its ecological significance, was set up to facilitate presentations, interactive sessions, and a field visit. AIH’s President, Hrvoje Mikulčić, led the planning and coordination efforts, starting with the development of a comprehensive agenda that included welcoming remarks, expert presentations, interactive sessions, and a networking lunch. The team managed the logistics of inviting and registering participants, including local and regional authorities, scientists, and policy sector representatives.
On the day of the workshop, AIH handled participant registration and provided informational materials. The event kicked off with welcome speeches by Hrvoje Mikulčić and a representative from Lonjsko Polje Nature Park, setting the stage for a series of presentations. These presentations, delivered by experts like Zlatko Nedić from CEKOM, Ivica Pavičić from RGN, and Filip Jurić from FSB, covered various aspects of the project, ecological problem-solving, sustainable solutions, and renewable energy in aquaculture. A coffee break was arranged to facilitate informal interactions and networking among the attendees.
The latter part of the workshop included a significant segment on the Mission Ocean, Seas, and Water platform, presented by Hrvoje Mikulčić and Zlatko Nedić, highlighting the importance of stakeholder involvement in the DaWetRest project. This was followed by an interactive session where participants worked together to identify the needs of wetland ecosystems and discuss sustainable solutions. The workshop concluded with a guided field tour of Lonjsko Polje, offering participants a practical perspective on ecosystem management, followed by a communal lunch that provided further opportunities for networking and discussions.
AIH also conducted follow-up activities to maintain engagement with stakeholders, addressing their queries and inviting further collaboration for the ongoing success of the DaWetRest project. Through careful planning, execution, and follow-up, AIH ensured the workshop was not only productive and informative but also fostered collaboration and stakeholder engagement crucial for the project’s objectives.

### Surveys

